
version: 2
jobs:
  build:
    working_directory: ~/sports-social-media-profile-locater/api
    docker:
      - image: python:3.7
    steps:
      - checkout
  test:
    working_directory: ~/sports-social-media-profile-locater/api
    docker:
      - image: python:3.7
    steps:
      - checkout:
          path: ~/sports-social-media-profile-locater
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            python -m unittest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test