
version: 2
jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - run:
          name: Run tests
          command: |
            pip install -r requirements.txt
            python -m unittest
          no_output_timeout: 1h
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  version: 2
  test_package:
    jobs:
      - test